### ISSUE TITLE
accepting PRs

### ISSUE THREAD

**Issue by andy5995** [roklein/htdig#1]
I see it's been some years since this has been worked on. Would you accept any PRs if they came your way, or would it be best if I made a separate fork if I decided to promote and continue this project?

**Comment by roklein** [comment]
Thank you for your interest in this project.  I think it's better you fork and continue there.  My repository is basically up to version 3.2b6 and some patches from further down the tree and those used by some major distributions (suse, fedora,...).  So in a way, this is probably the most stable version of htdig, currently.   Unfortunately it seems, I only put the one tree into the repository (I converted it from CVS), so the older 3.1.6 stuff isn't here.  Also the early 4.0 code is missing, but I think you are way better off, not using it.   Plese note, there is a fork from jrsupplee which has three additional patches.  I didn't review those, however, and  never got a pull request.

Best regards,
Robert

**Comment by andy5995** [comment]
Thanks a lot for the update, Robert, it helps.

I mirrored the repo two days ago (https://github.com/andy5995/htdig)

I couldn't make heads-nor-tails out of the 4_1_0 release, but what you say explains that.

I just tried building from your last commit; it failed so I applied a patch from Debian and now it's building.

Good luck with your future endeavors. You are of course welcome to join the Slack channel I created if you're ever curious about the current status and would like to passively monitor any progress.

TBH, I don't see anything significant happening with it for a while, maybe never. I'm not nearly skilled enough to do much with htdig, but I figure it may be a good side project for me, and perhaps other developers may find it interesting enough to work on.

Thanks again for giving me some clues to go on.

**Comment by andy5995** [comment]
Hi Robert,

So although this 4.1.0 branch exists, parts are missing?

https://github.com/solbu/hldig/tree/4_1_0

**Comment by roklein** [comment]
Hi Andy,

no, the ht://Dig 4 parts are missing from my repository.  You can still get the original CVS repository from sourceforge, everything the developers did should be there.

I was more interested in ht://Dig itself, not some Lucene+frontend stuff.  At least that's what the ht://Dig 4 stuff looked to me.

I don't think the ht://Dig 4 versions were part of any software distribution, e.g. Linux distributions, *BSD ports/packages and so on.  Debian and FreeBSD, for example, currently still have version 3.2.0b6.
